name: build

on:
  pull_request:

jobs:
  test:
    strategy:
      matrix:
        go: [ '1.19.x', '1.20.x', '1.21.x', '1.22.x' ]
        platform: [ubuntu-latest, macos-latest]
    runs-on: ${{ matrix.platform }}
    steps:
      - uses: actions/checkout@v4
      
      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: ${{ matrix.go }}
      
      - name: deps
        run:  make deps
      
      - name: static program analysis
        run: make fmt-check vet
      
      - name: build
        run: make build
      
      - name: test
        run: make test
